import DepositGateway from '#models/deposit_gateway';
import { BaseSeeder } from '@adonisjs/lucid/seeders';
export default class extends BaseSeeder {
    async run() {
        await DepositGateway.createMany([
            {
                name: 'MTN/Orange/Expresso/TMoney/Moov',
                value: 'paydunya',
                apiKey: 'live_public_ZGHqiWZIs7ISXAM0FotI9GTS0QP',
                secretKey: 'live_private_UlnCKEgLokaGdpVjrU63QkItgRG',
                isCrypto: false,
                active: true,
                activeApi: true,
                ex1: 'gYTKkNEO-Hylb-VErx-exre-HYlBYr89Cwaz',
                ex2: 'c7iCsRFb42s7Fambg2ac',
                allowedCurrencies: JSON.stringify(['XOF', 'XAF']),
                allowedCountries: JSON.stringify(['*']),
            },
            {
                name: 'Perfect Money',
                value: 'perfectmoney',
                isCrypto: false,
                active: true,
                activeApi: true,
                ex1: 'U35368357',
                ex2: 'E33172315',
                allowedCurrencies: JSON.stringify(['USD', 'EUR']),
                allowedCountries: JSON.stringify(['*']),
            },
            {
                name: 'Wave',
                value: 'wave',
                isCrypto: false,
                active: true,
                activeApi: true,
                apiKey: 'wave_ci_prod_H603eJ8V1x_mgAatq3n48AqaVsA4Wmziq6yFwVXSpHnZJlSMWvWvDjXQtbnqmNdVOmGLuoZCSGyrB73G_RpbjPtgSyJd3yVG-g',
                secretKey: 'WH_1g4WZ8AarA2I',
                allowedCurrencies: JSON.stringify(['XOF', 'XAF']),
                allowedCountries: JSON.stringify(['*']),
            },
            {
                name: 'Stripe',
                value: 'stripe',
                isCrypto: false,
                active: true,
                activeApi: true,
                allowedCountries: JSON.stringify(['*']),
                allowedCurrencies: JSON.stringify(['USD', 'EUR', 'GBP']),
                apiKey: 'sk_test_51JFcapDOao7iBpqLH42awxLJ6q0Kkw1A4FouIY3VkxsWpnhBaHsNTHmv3BLbiqClF4rn8zUHkt7gpyyjnqz6bzXW00vatkcqFB',
                secretKey: 'whsec_BfcvKT4mq9B1UZHSmDe2PxlrQuMcLpmM',
            },
            {
                name: 'Coinbase',
                value: 'coinbase',
                isCrypto: false,
                active: false,
                activeApi: false,
                allowedCountries: JSON.stringify(['*']),
                allowedCurrencies: JSON.stringify(['USD', 'EUR', 'GBP']),
                apiKey: '8ef6c4ca-f5c7-4717-9d9a-002adf7e7590',
            },
            {
                name: 'Flutterwave',
                value: 'flutterwave',
                isCrypto: false,
                active: true,
                activeApi: true,
                allowedCountries: JSON.stringify(['*']),
                allowedCurrencies: JSON.stringify([
                    'GBP',
                    'CAD',
                    'XAF',
                    'CLP',
                    'COP',
                    'EGP',
                    'EUR',
                    'GHS',
                    'GNF',
                    'KES',
                    'MWK',
                    'MAD',
                    'NGN',
                    'RWF',
                    'SLL',
                    'STD',
                    'ZAR',
                    'TZS',
                    'UGX',
                    'USD',
                    'XOF',
                    'ZMW',
                ]),
                apiKey: 'FLWPUBK_TEST-41515de1529b3e57403c56081294c82b-X',
                secretKey: 'FLWSECK_TEST-9b5ab94d39fb4fd1f286662837b8c4e6-X',
            },
            {
                name: 'PayPal',
                value: 'paypal',
                apiKey: 'ASAGxW7hVouAckSMmzYvWSUTShjcN_OUMgZc3LenAp8HcQXL54mKVhq0ZgQQohyBlatvUETn340pLBzq',
                secretKey: 'ENPBkT8f67VuTqR3Hb0zLrEskpMTIvNCxFycSr3ALE3Ntu6x_RWE1s8grDuxIF2Ip-Ra3oS2-Yzdf0cf',
                ex1: 'sandbox',
                ex2: '',
                active: true,
                activeApi: true,
                isCrypto: false,
                allowedCurrencies: JSON.stringify(['USD', 'EUR', 'GBP']),
                allowedCountries: JSON.stringify(['*']),
            },
            {
                name: 'Mollie',
                value: 'mollie',
                apiKey: 'test_bDCF5jfKAeqv3GReFvfMVRWm8M26aT',
                ex1: 'pfl_C3HSymV6pU',
                active: true,
                activeApi: true,
                isCrypto: false,
                allowedCurrencies: JSON.stringify(['USD', 'EUR', 'GBP', 'AUD', 'CAD']),
                allowedCountries: JSON.stringify(['*']),
            },
            {
                name: 'Razorpay',
                value: 'razorpay',
                apiKey: 'rzp_test_vo4D1tyVHUM9lq',
                secretKey: 'b9LW9Y2gGh11t0UTzUmrwGEa',
                active: true,
                activeApi: true,
                isCrypto: false,
                allowedCurrencies: JSON.stringify(['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'INR', 'SGD']),
                allowedCountries: JSON.stringify(['*']),
            },
            {
                name: 'Coingate',
                value: 'coingate',
                apiKey: 'JGZ7Z3Jng9eZT3oeLbRb7axqc_vWdW_yHeWXqVNy',
                ex1: 'sandbox',
                active: true,
                activeApi: true,
                isCrypto: true,
                allowedCurrencies: JSON.stringify([
                    'USD',
                    'BTC',
                    'EUR',
                    'GBP',
                    'PLN',
                    'CZK',
                    'SEK',
                    'NOK',
                    'DKK',
                    'CHF',
                    'ZAR',
                    'AUD',
                    'JPY',
                    'NZD',
                    'TRY',
                    'BRL',
                    'CAD',
                    'CNY',
                    'HKD',
                    'HUF',
                    'INR',
                    'RUB',
                    'ILS',
                    'MYR',
                    'MXN',
                    'SGD',
                    'RON',
                    'IDR',
                    'PHP',
                    'ARS',
                    'THB',
                    'NGN',
                    'PKR',
                    'AED',
                    'UAH',
                    'BGN',
                    'HRK',
                    'RSD',
                    'LTC',
                    'ETH',
                    'BCH',
                    'XRP',
                    'TWD',
                    'CLP',
                    'TRX',
                    'DAI',
                    'DOGE',
                    'BNB',
                    'USDT',
                    'AVA',
                    'KRW',
                    'EGP',
                    'SAR',
                    'QAR',
                    'POL',
                    'USDC',
                    'BUSD',
                    'SOL',
                    'SHIB',
                    'AVAX',
                    'ATOM',
                    'EGLD',
                    'FLOW',
                    'BTTC',
                    'ARB',
                ]),
                allowedCountries: JSON.stringify(['*']),
            },
            {
                name: 'NowPayments',
                value: 'nowpayments',
                apiKey: 'XPBQB4Y-B2EMV58-M2VG7WJ-XS5QFYG',
                active: true,
                activeApi: true,
                isCrypto: true,
                allowedCountries: JSON.stringify(['*']),
                allowedCurrencies: JSON.stringify(['BTC', 'ETH', 'BNB', 'USDT', 'USD', 'EUR']),
            },
            {
                name: 'bKash',
                value: 'bkash',
                apiKey: '4f6o0cjiki2rfm34kfdadl1eqq',
                secretKey: '2is7hdktrekvrbljjh44ll3d9l1dtjo4pasmjvs5vl5qr3fug4b',
                ex1: 'sandboxTokenizedUser02',
                ex2: 'sandboxTokenizedUser02@12345',
                active: true,
                activeApi: true,
                isCrypto: false,
                allowedCountries: JSON.stringify(['*']),
                allowedCurrencies: JSON.stringify(['BDT']),
            },
            {
                name: 'Paystack',
                value: 'paystack',
                apiKey: 'pk_test_22fc68c6f66b313514374a1fe886bc4a55e2370b',
                secretKey: 'sk_test_4ef1cd37058ffabe9468fc1a9a4e8fe21e36935f',
                active: true,
                activeApi: true,
                isCrypto: false,
                allowedCountries: JSON.stringify(['*']),
                allowedCurrencies: JSON.stringify(['NGN', 'GHS', 'ZAR', 'KES']),
            },
            {
                name: 'Cashfree Payments',
                value: 'cashfree',
                apiKey: 'TEST104777659f2faa219e9c9a92736856777401',
                secretKey: 'cfsk_ma_test_58ad065b6995f68b18619e053617e6bc_67bfe567',
                active: true,
                activeApi: true,
                isCrypto: false,
                allowedCountries: JSON.stringify(['*']),
                allowedCurrencies: JSON.stringify(['INR']),
            },
            {
                name: 'Payfast',
                value: 'payfast',
                apiKey: '10037105',
                secretKey: 'c346us3lwux56',
                ex1: 'sandbox',
                active: true,
                activeApi: true,
                isCrypto: false,
                allowedCountries: JSON.stringify(['*']),
                allowedCurrencies: JSON.stringify(['ZAR']),
            },
        ]);
    }
}
//# sourceMappingURL=gateway_seeder.js.map